# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Answer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, body: str=None, user_id: int=None, commentcount: int=None, creationdate: str=None, upvote: int=None, downvote: int=None):  # noqa: E501
        """Answer - a model defined in Swagger

        :param id: The id of this Answer.  # noqa: E501
        :type id: int
        :param body: The body of this Answer.  # noqa: E501
        :type body: str
        :param user_id: The user_id of this Answer.  # noqa: E501
        :type user_id: int
        :param commentcount: The commentcount of this Answer.  # noqa: E501
        :type commentcount: int
        :param creationdate: The creationdate of this Answer.  # noqa: E501
        :type creationdate: str
        :param upvote: The upvote of this Answer.  # noqa: E501
        :type upvote: int
        :param downvote: The downvote of this Answer.  # noqa: E501
        :type downvote: int
        """
        self.swagger_types = {
            'id': int,
            'body': str,
            'user_id': int,
            'commentcount': int,
            'creationdate': str,
            'upvote': int,
            'downvote': int
        }

        self.attribute_map = {
            'id': 'id',
            'body': 'body',
            'user_id': 'user_id',
            'commentcount': 'commentcount',
            'creationdate': 'creationdate',
            'upvote': 'upvote',
            'downvote': 'downvote'
        }

        self._id = id
        self._body = body
        self._user_id = user_id
        self._commentcount = commentcount
        self._creationdate = creationdate
        self._upvote = upvote
        self._downvote = downvote

    @classmethod
    def from_dict(cls, dikt) -> 'Answer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Answer of this Answer.  # noqa: E501
        :rtype: Answer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Answer.


        :return: The id of this Answer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Answer.


        :param id: The id of this Answer.
        :type id: int
        """

        self._id = id

    @property
    def body(self) -> str:
        """Gets the body of this Answer.


        :return: The body of this Answer.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Answer.


        :param body: The body of this Answer.
        :type body: str
        """

        self._body = body

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Answer.


        :return: The user_id of this Answer.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Answer.


        :param user_id: The user_id of this Answer.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def commentcount(self) -> int:
        """Gets the commentcount of this Answer.


        :return: The commentcount of this Answer.
        :rtype: int
        """
        return self._commentcount

    @commentcount.setter
    def commentcount(self, commentcount: int):
        """Sets the commentcount of this Answer.


        :param commentcount: The commentcount of this Answer.
        :type commentcount: int
        """

        self._commentcount = commentcount

    @property
    def creationdate(self) -> str:
        """Gets the creationdate of this Answer.


        :return: The creationdate of this Answer.
        :rtype: str
        """
        return self._creationdate

    @creationdate.setter
    def creationdate(self, creationdate: str):
        """Sets the creationdate of this Answer.


        :param creationdate: The creationdate of this Answer.
        :type creationdate: str
        """

        self._creationdate = creationdate

    @property
    def upvote(self) -> int:
        """Gets the upvote of this Answer.


        :return: The upvote of this Answer.
        :rtype: int
        """
        return self._upvote

    @upvote.setter
    def upvote(self, upvote: int):
        """Sets the upvote of this Answer.


        :param upvote: The upvote of this Answer.
        :type upvote: int
        """

        self._upvote = upvote

    @property
    def downvote(self) -> int:
        """Gets the downvote of this Answer.


        :return: The downvote of this Answer.
        :rtype: int
        """
        return self._downvote

    @downvote.setter
    def downvote(self, downvote: int):
        """Sets the downvote of this Answer.


        :param downvote: The downvote of this Answer.
        :type downvote: int
        """

        self._downvote = downvote
