# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Comment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, body: str=None, user_id: int=None, post_type_id: int=None, post_id: int=None):  # noqa: E501
        """Comment - a model defined in Swagger

        :param id: The id of this Comment.  # noqa: E501
        :type id: int
        :param body: The body of this Comment.  # noqa: E501
        :type body: str
        :param user_id: The user_id of this Comment.  # noqa: E501
        :type user_id: int
        :param post_type_id: The post_type_id of this Comment.  # noqa: E501
        :type post_type_id: int
        :param post_id: The post_id of this Comment.  # noqa: E501
        :type post_id: int
        """
        self.swagger_types = {
            'id': int,
            'body': str,
            'user_id': int,
            'post_type_id': int,
            'post_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'body': 'body',
            'user_id': 'user_id',
            'post_type_id': 'post_type_id',
            'post_id': 'post_id'
        }

        self._id = id
        self._body = body
        self._user_id = user_id
        self._post_type_id = post_type_id
        self._post_id = post_id

    @classmethod
    def from_dict(cls, dikt) -> 'Comment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Comment of this Comment.  # noqa: E501
        :rtype: Comment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Comment.


        :return: The id of this Comment.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Comment.


        :param id: The id of this Comment.
        :type id: int
        """

        self._id = id

    @property
    def body(self) -> str:
        """Gets the body of this Comment.


        :return: The body of this Comment.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Comment.


        :param body: The body of this Comment.
        :type body: str
        """

        self._body = body

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Comment.


        :return: The user_id of this Comment.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Comment.


        :param user_id: The user_id of this Comment.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def post_type_id(self) -> int:
        """Gets the post_type_id of this Comment.


        :return: The post_type_id of this Comment.
        :rtype: int
        """
        return self._post_type_id

    @post_type_id.setter
    def post_type_id(self, post_type_id: int):
        """Sets the post_type_id of this Comment.


        :param post_type_id: The post_type_id of this Comment.
        :type post_type_id: int
        """

        self._post_type_id = post_type_id

    @property
    def post_id(self) -> int:
        """Gets the post_id of this Comment.


        :return: The post_id of this Comment.
        :rtype: int
        """
        return self._post_id

    @post_id.setter
    def post_id(self, post_id: int):
        """Sets the post_id of this Comment.


        :param post_id: The post_id of this Comment.
        :type post_id: int
        """

        self._post_id = post_id
