# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Questiontags(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, tagid: str=None, qn_id: int=None):  # noqa: E501
        """Questiontags - a model defined in Swagger

        :param id: The id of this Questiontags.  # noqa: E501
        :type id: int
        :param tagid: The tagid of this Questiontags.  # noqa: E501
        :type tagid: str
        :param qn_id: The qn_id of this Questiontags.  # noqa: E501
        :type qn_id: int
        """
        self.swagger_types = {
            'id': int,
            'tagid': str,
            'qn_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'tagid': 'tagid',
            'qn_id': 'qn_id'
        }

        self._id = id
        self._tagid = tagid
        self._qn_id = qn_id

    @classmethod
    def from_dict(cls, dikt) -> 'Questiontags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The questiontags of this Questiontags.  # noqa: E501
        :rtype: Questiontags
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Questiontags.


        :return: The id of this Questiontags.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Questiontags.


        :param id: The id of this Questiontags.
        :type id: int
        """

        self._id = id

    @property
    def tagid(self) -> str:
        """Gets the tagid of this Questiontags.


        :return: The tagid of this Questiontags.
        :rtype: str
        """
        return self._tagid

    @tagid.setter
    def tagid(self, tagid: str):
        """Sets the tagid of this Questiontags.


        :param tagid: The tagid of this Questiontags.
        :type tagid: str
        """

        self._tagid = tagid

    @property
    def qn_id(self) -> int:
        """Gets the qn_id of this Questiontags.


        :return: The qn_id of this Questiontags.
        :rtype: int
        """
        return self._qn_id

    @qn_id.setter
    def qn_id(self, qn_id: int):
        """Sets the qn_id of this Questiontags.


        :param qn_id: The qn_id of this Questiontags.
        :type qn_id: int
        """

        self._qn_id = qn_id
