# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Question(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, title: str=None, body: str=None, question_tags: object=None, user_id: int=None, answercount: int=None, commentcount: int=None, answeracceptedid: int=None, creationdate: str=None, upvote: int=None, downvote: int=None):  # noqa: E501
        """Question - a model defined in Swagger

        :param id: The id of this Question.  # noqa: E501
        :type id: int
        :param title: The title of this Question.  # noqa: E501
        :type title: str
        :param body: The body of this Question.  # noqa: E501
        :type body: str
        :param question_tags: The question_tags of this Question.  # noqa: E501
        :type question_tags: object
        :param user_id: The user_id of this Question.  # noqa: E501
        :type user_id: int
        :param answercount: The answercount of this Question.  # noqa: E501
        :type answercount: int
        :param commentcount: The commentcount of this Question.  # noqa: E501
        :type commentcount: int
        :param answeracceptedid: The answeracceptedid of this Question.  # noqa: E501
        :type answeracceptedid: int
        :param creationdate: The creationdate of this Question.  # noqa: E501
        :type creationdate: str
        :param upvote: The upvote of this Question.  # noqa: E501
        :type upvote: int
        :param downvote: The downvote of this Question.  # noqa: E501
        :type downvote: int
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'body': str,
            'question_tags': object,
            'user_id': int,
            'answercount': int,
            'commentcount': int,
            'answeracceptedid': int,
            'creationdate': str,
            'upvote': int,
            'downvote': int
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'body': 'body',
            'question_tags': 'question_tags',
            'user_id': 'user_id',
            'answercount': 'answercount',
            'commentcount': 'commentcount',
            'answeracceptedid': 'answeracceptedid',
            'creationdate': 'creationdate',
            'upvote': 'upvote',
            'downvote': 'downvote'
        }

        self._id = id
        self._title = title
        self._body = body
        self._question_tags = question_tags
        self._user_id = user_id
        self._answercount = answercount
        self._commentcount = commentcount
        self._answeracceptedid = answeracceptedid
        self._creationdate = creationdate
        self._upvote = upvote
        self._downvote = downvote

    @classmethod
    def from_dict(cls, dikt) -> 'Question':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Question of this Question.  # noqa: E501
        :rtype: Question
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Question.


        :return: The id of this Question.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Question.


        :param id: The id of this Question.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Question.


        :return: The title of this Question.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Question.


        :param title: The title of this Question.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this Question.


        :return: The body of this Question.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Question.


        :param body: The body of this Question.
        :type body: str
        """

        self._body = body

    @property
    def question_tags(self) -> object:
        """Gets the question_tags of this Question.


        :return: The question_tags of this Question.
        :rtype: object
        """
        return self._question_tags

    @question_tags.setter
    def question_tags(self, question_tags: object):
        """Sets the question_tags of this Question.


        :param question_tags: The question_tags of this Question.
        :type question_tags: object
        """

        self._question_tags = question_tags

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Question.


        :return: The user_id of this Question.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Question.


        :param user_id: The user_id of this Question.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def answercount(self) -> int:
        """Gets the answercount of this Question.


        :return: The answercount of this Question.
        :rtype: int
        """
        return self._answercount

    @answercount.setter
    def answercount(self, answercount: int):
        """Sets the answercount of this Question.


        :param answercount: The answercount of this Question.
        :type answercount: int
        """

        self._answercount = answercount

    @property
    def commentcount(self) -> int:
        """Gets the commentcount of this Question.


        :return: The commentcount of this Question.
        :rtype: int
        """
        return self._commentcount

    @commentcount.setter
    def commentcount(self, commentcount: int):
        """Sets the commentcount of this Question.


        :param commentcount: The commentcount of this Question.
        :type commentcount: int
        """

        self._commentcount = commentcount

    @property
    def answeracceptedid(self) -> int:
        """Gets the answeracceptedid of this Question.


        :return: The answeracceptedid of this Question.
        :rtype: int
        """
        return self._answeracceptedid

    @answeracceptedid.setter
    def answeracceptedid(self, answeracceptedid: int):
        """Sets the answeracceptedid of this Question.


        :param answeracceptedid: The answeracceptedid of this Question.
        :type answeracceptedid: int
        """

        self._answeracceptedid = answeracceptedid

    @property
    def creationdate(self) -> str:
        """Gets the creationdate of this Question.


        :return: The creationdate of this Question.
        :rtype: str
        """
        return self._creationdate

    @creationdate.setter
    def creationdate(self, creationdate: str):
        """Sets the creationdate of this Question.


        :param creationdate: The creationdate of this Question.
        :type creationdate: str
        """

        self._creationdate = creationdate

    @property
    def upvote(self) -> int:
        """Gets the upvote of this Question.


        :return: The upvote of this Question.
        :rtype: int
        """
        return self._upvote

    @upvote.setter
    def upvote(self, upvote: int):
        """Sets the upvote of this Question.


        :param upvote: The upvote of this Question.
        :type upvote: int
        """

        self._upvote = upvote

    @property
    def downvote(self) -> int:
        """Gets the downvote of this Question.


        :return: The downvote of this Question.
        :rtype: int
        """
        return self._downvote

    @downvote.setter
    def downvote(self, downvote: int):
        """Sets the downvote of this Question.


        :param downvote: The downvote of this Question.
        :type downvote: int
        """

        self._downvote = downvote
