# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, username: str=None, email: str=None, imageurl: str=None, about: str=None, password: str=None, creationdate: str=None, reputation_points: int=None, follower: int=None, following: int=None, badges: object=None):  # noqa: E501
        """User - a model defined in Swagger

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param imageurl: The imageurl of this User.  # noqa: E501
        :type imageurl: str
        :param about: The about of this User.  # noqa: E501
        :type about: str
        :param password: The password of this User.  # noqa: E501
        :type password: str
        :param creationdate: The creationdate of this User.  # noqa: E501
        :type creationdate: str
        :param reputation_points: The reputation_points of this User.  # noqa: E501
        :type reputation_points: int
        :param follower: The follower of this User.  # noqa: E501
        :type follower: int
        :param following: The following of this User.  # noqa: E501
        :type following: int
        :param badges: The badges of this User.  # noqa: E501
        :type badges: object
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'email': str,
            'imageurl': str,
            'about': str,
            'password': str,
            'creationdate': str,
            'reputation_points': int,
            'follower': int,
            'following': int,
            'badges': object
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'email': 'email',
            'imageurl': 'imageurl',
            'about': 'about',
            'password': 'password',
            'creationdate': 'creationdate',
            'reputation_points': 'reputation_points',
            'follower': 'follower',
            'following': 'following',
            'badges': 'badges'
        }

        self._id = id
        self._username = username
        self._email = email
        self._imageurl = imageurl
        self._about = about
        self._password = password
        self._creationdate = creationdate
        self._reputation_points = reputation_points
        self._follower = follower
        self._following = following
        self._badges = badges

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def imageurl(self) -> str:
        """Gets the imageurl of this User.


        :return: The imageurl of this User.
        :rtype: str
        """
        return self._imageurl

    @imageurl.setter
    def imageurl(self, imageurl: str):
        """Sets the imageurl of this User.


        :param imageurl: The imageurl of this User.
        :type imageurl: str
        """

        self._imageurl = imageurl

    @property
    def about(self) -> str:
        """Gets the about of this User.


        :return: The about of this User.
        :rtype: str
        """
        return self._about

    @about.setter
    def about(self, about: str):
        """Sets the about of this User.


        :param about: The about of this User.
        :type about: str
        """

        self._about = about

    @property
    def password(self) -> str:
        """Gets the password of this User.


        :return: The password of this User.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this User.


        :param password: The password of this User.
        :type password: str
        """

        self._password = password

    @property
    def creationdate(self) -> str:
        """Gets the creationdate of this User.


        :return: The creationdate of this User.
        :rtype: str
        """
        return self._creationdate

    @creationdate.setter
    def creationdate(self, creationdate: str):
        """Sets the creationdate of this User.


        :param creationdate: The creationdate of this User.
        :type creationdate: str
        """

        self._creationdate = creationdate

    @property
    def reputation_points(self) -> int:
        """Gets the reputation_points of this User.


        :return: The reputation_points of this User.
        :rtype: int
        """
        return self._reputation_points

    @reputation_points.setter
    def reputation_points(self, reputation_points: int):
        """Sets the reputation_points of this User.


        :param reputation_points: The reputation_points of this User.
        :type reputation_points: int
        """

        self._reputation_points = reputation_points

    @property
    def follower(self) -> int:
        """Gets the follower of this User.


        :return: The follower of this User.
        :rtype: int
        """
        return self._follower

    @follower.setter
    def follower(self, follower: int):
        """Sets the follower of this User.


        :param follower: The follower of this User.
        :type follower: int
        """

        self._follower = follower

    @property
    def following(self) -> int:
        """Gets the following of this User.


        :return: The following of this User.
        :rtype: int
        """
        return self._following

    @following.setter
    def following(self, following: int):
        """Sets the following of this User.


        :param following: The following of this User.
        :type following: int
        """

        self._following = following

    @property
    def badges(self) -> object:
        """Gets the badges of this User.


        :return: The badges of this User.
        :rtype: object
        """
        return self._badges

    @badges.setter
    def badges(self, badges: object):
        """Sets the badges of this User.


        :param badges: The badges of this User.
        :type badges: object
        """

        self._badges = badges
