# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Usertags(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, tagid: str=None, user_id: int=None):  # noqa: E501
        """Usertags - a model defined in Swagger

        :param id: The id of this Usertags.  # noqa: E501
        :type id: int
        :param tagid: The tagid of this Usertags.  # noqa: E501
        :type tagid: str
        :param user_id: The user_id of this Usertags.  # noqa: E501
        :type user_id: int
        """
        self.swagger_types = {
            'id': int,
            'tagid': str,
            'user_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'tagid': 'tagid',
            'user_id': 'user_id'
        }

        self._id = id
        self._tagid = tagid
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Usertags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The usertags of this Usertags.  # noqa: E501
        :rtype: Usertags
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Usertags.


        :return: The id of this Usertags.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Usertags.


        :param id: The id of this Usertags.
        :type id: int
        """

        self._id = id

    @property
    def tagid(self) -> str:
        """Gets the tagid of this Usertags.


        :return: The tagid of this Usertags.
        :rtype: str
        """
        return self._tagid

    @tagid.setter
    def tagid(self, tagid: str):
        """Sets the tagid of this Usertags.


        :param tagid: The tagid of this Usertags.
        :type tagid: str
        """

        self._tagid = tagid

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Usertags.


        :return: The user_id of this Usertags.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Usertags.


        :param user_id: The user_id of this Usertags.
        :type user_id: int
        """

        self._user_id = user_id
